### ISSUE TITLE
Compatibility issues with TypeScript v2.4.1

### ISSUE THREAD

**Issue by Manusan42** [SierraSoftworks/Iridium#86]
Hello again,
I would like to use the newest version of TypeScript but the more strict generics checks results in some errors for the iridium module. This is what I get:
```bash
node_modules/iridium/dist/lib/cacheControllers/IDDirector.d.ts(8,22): error TS2420: Class 'CacheOnID' incorrectly implements interface 'CacheDirector'.
  Types of property 'valid' are incompatible.
    Type '(object: { [prop: string]: any; _id: any; }) => boolean' is not assignable to type '<T>(object: T) => boolean'.
      Types of parameters 'object' and 'object' are incompatible.
        Type 'T' is not assignable to type '{ [prop: string]: any; _id: any; }'.
node_modules/iridium/dist/lib/caches/NoOpCache.d.ts(11,22): error TS2420: Class 'NoOpCache' incorrectly implements interface 'Cache'.
  Types of property 'get' are incompatible.
    Type '<T>(key: string) => Bluebird<void>' is not assignable to type '<T>(key: string) => PromiseLike<T>'.
      Type 'Bluebird<void>' is not assignable to type 'PromiseLike<T>'.
        Types of property 'then' are incompatible.
          Type '{ <U>(onFulfill?: ((value: void) => U | PromiseLike<U>) | undefined, onReject?: ((error: any) => ...' is not assignable to type '<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T
) => TResult1 | PromiseLike<TResult1>) |...'.
            Types of parameters 'onFulfill' and 'onfulfilled' are incompatible.
              Type '((value: T) => any) | null | undefined' is not assignable to type '((value: void) => any) | undefined'.
                Type 'null' is not assignable to type '((value: void) => any) | undefined'.
```
Would be really nice if you have the time to fix this in near future.

Best regards,
Manuel

**Comment by SPARTAN563** [comment]
Hi Manuel,

I'll take a look quick and see if I can reproduce and fix the issue for you.

**Comment by SPARTAN563** [comment]
Hi Manuel,

Sorry that this took a while, turns out there was quite a lot of stuff that blew up as a result of what, at least on the surface, appears to be a small change to TypeScript's compiler. I've put together a series of changes which should enable Iridium to work with TypeScript 2.4+ as part of the Version 8.0.0 release milestone and released the initial version of that (which includes #83) as `iridium@8.0.0-alpha.1`

You can upgrade to the latest version of the alpha by running the following:

```sh
npm install --save iridium@next
```

Please have a look and let me know if anything unexpected breaks for you, there were a few changes I needed to make in tests that (incorrectly) assumed certain things to make the compiler happy, so I think any issues should only be for the greater good, however I'd love to hear of any exceptions to that.

I'll be holding v8 in alpha until I can get a decent amount of real world testing done on it, but I'll try to keep that codepath as stable as possible. If you'd prefer to remain on v7, I'd ask that you use the `--noStrictGenericChecks` compiler flag for the time being.

**Comment by Manusan42** [comment]
Firstly, your effort kinda blows me away. I'm really happy that I've choosen iridium for my project which was delivered with the best support I've seen so far ;-)

I'm totally ok with using the alpha version of 8.0 because my project is yet far away from any stable, but I sadly need to announce that I still get one error:
```bash
node_modules/iridium/dist/lib/caches/NoOpCache.d.ts(11,22): error TS2420: Class 'NoOpCache' incorrectly implements interface 'Cache'.
  Types of property 'get' are incompatible.
    Type '<T>(key: string) => Bluebird<void>' is not assignable to type '<T>(key: string) => PromiseLike<T>'.
      Type 'Bluebird<void>' is not assignable to type 'PromiseLike<T>'.
        Types of property 'then' are incompatible.
          Type '{ <U>(onFulfill?: ((value: void) => U | PromiseLike<U>) | undefined, onReject?: ((error: any) => ...' is not assignable to type '<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T
) => TResult1 | PromiseLike<TResult1>) |...'.
            Types of parameters 'onFulfill' and 'onfulfilled' are incompatible.
              Type '((value: T) => any) | null | undefined' is not assignable to type '((value: void) => any) | undefined'.
                Type 'null' is not assignable to type '((value: void) => any) | undefined'.
```

Thank you so much and no need to rush anything.

**Comment by SPARTAN563** [comment]
Hi @Manusan42

No worries at all and glad I can be of help. Let me see if I can reproduce that error, it's possible that it is caused by a more recent Bluebird definitions file than the one I tested with, however interestingly, the [build](https://travis-ci.org/SierraSoftworks/Iridium/builds/251771688) ran quite happily.

*EDIT*: After updating my Bluebird type definitions, I did indeed encounter the issue you're hitting. I've updated the cache API definitions to resolve those issues and pushed `8.0.0-alpha.2`, please let me know if that resolves your issue.

**Comment by Manusan42** [comment]
Super! It's working now, thanks again.
